# diskover es field copier default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_esfieldcopier and ~/Library/Application Support/diskover_esfieldcopier
# Other Unix: ~/.config/diskover_esfieldcopier and /etc/diskover_esfieldcopier
# Windows: %APPDATA%\diskover_esfieldcopier where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_esfieldcopier
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: False
#logToFile: True
logDirectory: /var/log/diskover/
# Windows: 
#logDirectory: C:\Program Files\diskover\logs

# max number of threads used for field copying
maxthreads: 4
# copy file and directory doc fields, set to True to copy or False to not copy
filefields: True
directoryfields: True
# a list of fields you want to copy, can be overwritten with cli option -f, --field
fieldstocopy: ['fieldname1', 'fieldname2']
# overwrite existing fields in target index if they exist with values in fields from source index
overwriteexisting: True