# diskover es query report default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_esqueryreport and ~/Library/Application Support/diskover_esqueryreport
# Other Unix: ~/.config/diskover_esqueryreport and /etc/diskover_esqueryreport
# Windows: %APPDATA%\diskover_esqueryreport where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_esqueryreport
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: False
#logToFile: True
logDirectory: /var/log/diskover/
# Windows: 
#logDirectory: C:\Program Files\diskover\logs

# csv file name format
# %indexname is replaced with index name used in cli arg
# uses python datetime strftime format codes for Year, Month, Day, etc
csvfile: diskover-esqueryreport-%indexname-%m%d%Y_%H%M%S.csv
# directory to store csv files in
csvdir: /tmp/
# Windows: 
#csvdir: C:\Windows\Temp
# ES doc fields to include in csv
# name for file name
# extension for file extension
# parent_path for parent path
# size for file size
# size_du for allocated file size
# owner for file owner
# group for group owner
# mtime for modified time
# atime for access time
# ctime for change time
# nlink for number of hardlinks
# ino for inode number
# costpergb for cost per gb
# type for file or directory
# tags for doc tags
# hash for file hash (dupes finder plugin)
# is_dupe for is duplicate (dupes finder plugin)
# media_info for media info (media info plugin)
# unix_perms for unix perms (unix perms plugin)
# etc.
docfields: ['name', 'parent_path', 'extension', 'type', 'size', 'size_du', 'mtime', 'tags']
# make human readable sizes in csv report (GB, MB, KB, etc) instead of just bytes, True or False
humansizes: True
# email settings
# send email, True or False
sendemail: True
# email sender address
emailfrom: user@domain.com
# email recipient address, comma separated for multiple recipients
emailto: user@domain.com
# email subject
emailsubject: Diskover ES Query Report
# email html body message, use %esquery to include ES query used for report
emailmsg: '<b>Diskover ES Query Report</b><br>Query: %esquery'
# attach csv file to email, True or False
attachcsv: True
# zip csv, True or False
zipcsv: True
# delete csv file after zipping
delcsv: False
# email server settings
# smtp server host name/ip
smtpserver: 
# smtp server port, defaults are 465 for SSL and 587 for TLS
smtpport: 465
# smtp security SSL, TLS or None
smtpsecurity: SSL
# user name for smtp server auth
smtpuser: 
# password for smtp server auth
smtppassword: 