# diskover indexdiff default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_indexdiff and ~/Library/Application Support/diskover_indexdiff
# Other Unix: ~/.config/diskover_indexdiff and /etc/diskover_indexdiff
# Windows: %APPDATA%\diskover_indexdiff where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_indexdiff
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: False
#logToFile: True
logDirectory: /var/log/diskover/

# --es2 cli option settings
# optional es host where index2 lives
es2host: 
es2port: 9200
es2user: 
es2password: 
# if the es host uses HTTP TLS/SSL, set es2https to True
es2https: False
# --hashdiff cli option settings
# skip files with empty/no hash
# set to True to not compare files with no hash or False to compare
hashskipempty: True
# skip files that are missing in either index (new file)
# set to True to skip new files that don't exist, or False to include them in diffs
hashskipmissing: True
# directory to save csv files
csvdir: /tmp