# diskover autotag default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_autotag and ~/Library/Application Support/diskover_autotag
# Other Unix: ~/.config/diskover_autotag and /etc/diskover_autotag
# Windows: %APPDATA%\diskover_autotag where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_autotag
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: False
#logToFile: True
logDirectory: /var/log/diskover/
# Windows: 
#logDirectory: C:\Program Files\diskover\logs

# max number of threads used for autotagging
maxthreads: 4
# search queries to use when auto-tagging and tags to assign to the results for both file and directory docs
#files: 
#dirs: 
dirs: [
        {
        'query': 'mtime:{* TO now/m-6M/d}',
        'tags': ['autotag', 'archive']
        },
        {
        'query': 'name:(*tmp* OR *TMP* OR *temp* OR *TEMP* OR *Temp* OR *cache* OR *CACHE* OR *Cache*) AND mtime:{* TO now/m-2M/d}',
        'tags': ['autotag', 'delete']
        }
    ]
files: [
        {
        'query': 'extension:(tmp* OR temp* OR cache* OR bak* OR old* OR delete*) AND mtime:{* TO now/m-6M/d} AND atime:{* TO now/m-6M/d}',
        'tags': ['autotag', 'cleanlist', 'delete']
        },
        {
        'query': 'mtime:{* TO now/m-6M/d}',
        'tags': ['autotag', 'archive']
        }
    ]