# diskover s3 checksums default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_s3_checksums and ~/Library/Application Support/diskover_s3_checksums
# Other Unix: ~/.config/diskover_s3_checksums and /etc/diskover_s3_checksums
# Windows: %APPDATA%\diskover_s3_checksums where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_s3_checksums
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: False
#logToFile: True
logDirectory: /var/log/diskover/

# The api endpoint of the fixity cloud formation stack
# https://github.com/awslabs/serverless-fixity-for-digital-preservation-compliance
fixity_api_endpoint: 'https://xxxxxxx.execute-api.us-west-1.amazonaws.com/demo/fixity'
# max number of workers for file hashing
workers: 100
# the interval in which to check if a worker has completed the hash process.
check_interval: 30
# which hash/checksum type to use, config setting can be overwritten with --hashmode cli option
# hash modes: md5, sha1
# checksums are stored in the hash field: hash.md5, hash.sha1
hash_mode: md5
# cache directory to store cache db (sqlite3)
# can be set to absolute or relative path (relative to where diskover-s3-checksums.py is run)
#cache_dir: __diskover_s3_hash_cache__/
cache_dir: /opt/diskover/plugins_postindex/__diskover_s3_hash_cache__/
# cached item's expiry time in seconds or leave empty to never expire
cache_expiretime:
