# diskover offline media default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_offline_media and ~/Library/Application Support/diskover_offline_media
# Other Unix: ~/.config/diskover_offline_media and /etc/diskover_offline_media
# Windows: %APPDATA%\diskover_offline_media where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_offline_media
root_path: /OFFLINE_MEDIA

# verbose output logging, set to True or False
verbose: False
# cache directory to store cache db (sqlite3)
# can be set to absolute or relative path (relative to where diskover.py is run)
#cachedir: __dircache__/
cachedir: /opt/diskover/__dircache_offline_media__/
# Windows:
#cachedir: C:\Program Files\diskover\__dircache__
# expiry time in seconds for dir list cache, or 0 to not expire
# directory mtimes are always checked and if mtime on disk does not match
# mtime in cache, directory is re-scanned
dirlist_expire: 0
# load sqlite3 db file into memory at start
# setting this to True can cause sqlite db corruption issues if scan crashes, recommended set to False
load_db_mem: False