# diskover costs default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskover_costs and ~/Library/Application Support/diskover_costs
# Other Unix: ~/.config/diskover_costs and /etc/diskover_costs
# Windows: %APPDATA%\diskover_costs where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskover_costs
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: False
#logToFile: True
logDirectory: /var/log/diskover/
# Windows: 
#logDirectory: C:\Program Files\diskover\logs

# max number of threads used for updating costs
maxthreads: 4
# use decimal base 10 (1000) or binary base 2 (1024) for GB size (set to 2 or 10)
base: 2
# use size or size_du (disk usage) field for calculating costs
sizefield: size_du
# search queries and cost to use when updating costpergb field
costs: [
        {
        'query': 'parent_path:\/somedir1*',
        'cost': 0.80
        },
        {
        'query': 'parent_path:\/somedir2*',
        'cost': 0.20
        }
    ]