# diskoverd daemon default/sample config file
#
# default search paths for config
# macOS: ~/.config/diskoverd and ~/Library/Application Support/diskoverd
# Other Unix: ~/.config/diskoverd and /etc/diskoverd
# Windows: %APPDATA%\diskoverd where the APPDATA environment variable falls back to %HOME%\AppData\Roaming if undefined
#
appName: diskoverd
#logLevel: WARN
#logLevel: DEBUG
logLevel: INFO
logToFile: True
#logToFile: False
logDirectory: /var/log/diskover/
# Windows: 
#logDirectory: C:\Program Files\diskover\logs

# local TZ timezone name https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Vancouver
# number of work threads that will run simultanous tasks
# set this to tne max number of tasks you want diskoverd to run at the same time
workthreads: 4
# path to python3, or python3 if in PATH
pythoncmd: python3
# Windows: 
#pythoncmd: python
# path to diskover python app
diskoverpath: /opt/diskover/
# Windows: 
#diskoverpath: C:\\Program\ Files\\diskover\\
# diskover-web api url
apiurl: http://localhost:8000/api.php
# diskover-web api username, leave empty for no user auth
#apiuser: diskoverapi
apiuser: 
# diskover-web api password
#apipass: apisecret
apipass: 
# email server settings
# smtp server host name/ip
smtpserver: 
# smtp server port, defaults are 465 for SSL and 587 for TLS
smtpport: 465
# smtp security SSL, TLS or None
smtpsecurity: SSL
# user name for smtp server auth
smtpuser: 
# password for smtp server auth
smtppassword: 
# sender email address
senderemail: 
# send emails on task completions only, task failures only, all or none
# set to all for both fail/complete, fail for failures, finish for completions, or none to not send any email
sendemail: none
# send email when task taking more than n minutes to run
# set to number of minutes, or none to not send any email
sendemaillongruntask: 1440
# replace file/directory paths for file action tasks
replacepaths:
    # translate path names set to True to enable or False to disable.
    # Set to True if running in Windows to replace / with \ and add drive letter prefix
    replace: False
    #from: /Z_drive
    #to:  Z:
    from:
    to:
# task worker pools
# can assign task workers to different pools, default is not assigned to any pools (empty list [])
# example to assign diskoverd worker to a pool named site1-pool, set workerpools list to ['site1-pool']
workerpools: []